services:
  server:
    image: ghcr.io/rootenginear/learn-ghcr:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.routers.server.rule=Host(`localhost`)"

  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
